name: Java CI with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_jar:
    name: Build JAR

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Upload jar as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ms-orchestrator-1.0.0.jar
        path: target/ms-orchestrator-1.0.0.jar
        retention-days: 1