name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Push Docker Image

    runs-on: ubuntu-latest
    environment: mvp

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
    - name: Authenticate Docker to Amazon ECR Public
      run: |
      aws ecr-public get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin public.ecr.aws/${{ secrets.ECR_PUBLIC_ID }}
    - name: Build Docker image
      run: |
      docker build -t ms-orchestrator:1.0.0 .
    - name: Tag Docker image
      run: |
      docker tag ms-orchestrator:1.0.0 public.ecr.aws/${{ secrets.ECR_PUBLIC_ID }}/ms-orchestrator:latest
    - name: Push Docker image to Amazon ECR Public
      run: |
      docker push public.ecr.aws/${{ secrets.ECR_PUBLIC_ID }}/ms-orchestrator:latest